# Generated by Django 6.1.1 on 2026-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
